# coding: utf-8

"""
    PharmaTrace Supply Chain Information Network API

    The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: api@pharmatrace.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.activitys_api import ActivitysApi  # noqa: E501
from openapi_client.rest import ApiException


class TestActivitysApi(unittest.TestCase):
    """ActivitysApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.activitys_api.ActivitysApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_activity(self):
        """Test case for add_activity

        """
        pass

    def test_delete_activity(self):
        """Test case for delete_activity

        """
        pass

    def test_find_activity_by_id(self):
        """Test case for find_activity_by_id

        """
        pass

    def test_find_activitys(self):
        """Test case for find_activitys

        """
        pass


if __name__ == '__main__':
    unittest.main()
