# coding: utf-8

"""
    PharmaTrace Supply Chain Information Network API

    The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: api@pharmatrace.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.io.pharmatrace.api.scin.public.model.transport import Transport  # noqa: E501
from openapi_client.rest import ApiException


class TestTransport(unittest.TestCase):
    """Transport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransport(self):
        """Test Transport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.transport.Transport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
