# coding: utf-8

"""
    PharmaTrace Supply Chain Information Network API

    The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: api@pharmatrace.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from io.pharmatrace.api.scin.public.api.information_query_responses_api import InformationQueryResponsesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestInformationQueryResponsesApi(unittest.TestCase):
    """InformationQueryResponsesApi unit test stubs"""

    def setUp(self):
        self.api = io.pharmatrace.api.scin.public.api.information_query_responses_api.InformationQueryResponsesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_information_query_response(self):
        """Test case for add_information_query_response

        """
        pass

    def test_delete_information_query_response(self):
        """Test case for delete_information_query_response

        """
        pass

    def test_find_information_query_responses(self):
        """Test case for find_information_query_responses

        """
        pass

    def test_find_informationqueryresponse_by_id(self):
        """Test case for find_informationqueryresponse_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
