# coding: utf-8

"""
    PharmaTrace Supply Chain Information Network API

    The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: api@pharmatrace.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Wallet(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'balance': 'float',
        'wallet_id': 'str',
        'display_name': 'str',
        'owner_stakeholder_id': 'str'
    }

    attribute_map = {
        'balance': 'balance',
        'wallet_id': 'wallet_id',
        'display_name': 'display_name',
        'owner_stakeholder_id': 'owner_stakeholder_id'
    }

    def __init__(self, balance=None, wallet_id=None, display_name=None, owner_stakeholder_id=None):  # noqa: E501
        """Wallet - a model defined in OpenAPI"""  # noqa: E501

        self._balance = None
        self._wallet_id = None
        self._display_name = None
        self._owner_stakeholder_id = None
        self.discriminator = None

        if balance is not None:
            self.balance = balance
        if wallet_id is not None:
            self.wallet_id = wallet_id
        if display_name is not None:
            self.display_name = display_name
        if owner_stakeholder_id is not None:
            self.owner_stakeholder_id = owner_stakeholder_id

    @property
    def balance(self):
        """Gets the balance of this Wallet.  # noqa: E501

        current balance  # noqa: E501

        :return: The balance of this Wallet.  # noqa: E501
        :rtype: float
        """
        return self._balance

    @balance.setter
    def balance(self, balance):
        """Sets the balance of this Wallet.

        current balance  # noqa: E501

        :param balance: The balance of this Wallet.  # noqa: E501
        :type: float
        """

        self._balance = balance

    @property
    def wallet_id(self):
        """Gets the wallet_id of this Wallet.  # noqa: E501

        wallet uuid  # noqa: E501

        :return: The wallet_id of this Wallet.  # noqa: E501
        :rtype: str
        """
        return self._wallet_id

    @wallet_id.setter
    def wallet_id(self, wallet_id):
        """Sets the wallet_id of this Wallet.

        wallet uuid  # noqa: E501

        :param wallet_id: The wallet_id of this Wallet.  # noqa: E501
        :type: str
        """

        self._wallet_id = wallet_id

    @property
    def display_name(self):
        """Gets the display_name of this Wallet.  # noqa: E501

        descriptive name of the wallet so user can identify it if s/he has multiple wallets  # noqa: E501

        :return: The display_name of this Wallet.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this Wallet.

        descriptive name of the wallet so user can identify it if s/he has multiple wallets  # noqa: E501

        :param display_name: The display_name of this Wallet.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def owner_stakeholder_id(self):
        """Gets the owner_stakeholder_id of this Wallet.  # noqa: E501

        id of the wallet owner (normally an organization  # noqa: E501

        :return: The owner_stakeholder_id of this Wallet.  # noqa: E501
        :rtype: str
        """
        return self._owner_stakeholder_id

    @owner_stakeholder_id.setter
    def owner_stakeholder_id(self, owner_stakeholder_id):
        """Sets the owner_stakeholder_id of this Wallet.

        id of the wallet owner (normally an organization  # noqa: E501

        :param owner_stakeholder_id: The owner_stakeholder_id of this Wallet.  # noqa: E501
        :type: str
        """

        self._owner_stakeholder_id = owner_stakeholder_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Wallet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
